### ISSUE TITLE
E39_Actor sex v. gender

### ISSUE THREAD

**Issue by cbutcosk** [american-art/aac_mappings#47]
I propose that "gender" in the E39_Actor mapping be renamed "sex" or "biological sex" since it draws that field from ULAN's biography nodes that map sex distinctions as an agent's gender.

I know that gender distinctions are tricky, but where ULAN maps gender, it points to objects of sexual distinction. schema:gender predicates point to terms of sexual distinction--mostly http://vocab.getty.edu/aat/300189559 ("male") and http://vocab.getty.edu/aat/300189557 ("female"), though some "unknown" or "other" objects exist. These are both sexual distinctions (see http://www.getty.edu/vow/AATHierarchy?find=&logic=AND&note=&page=1&subjectid=300055146 where you can see the unused term from that hierarchy--hermaphroditism!).

Without a model capable of making finer distinctions between instances of gender (say, an event- or utterance-based one that would distinguish between Marcel Duchamp's persona as a male artist and his feminine alter-ego Rose Sélavy) I think the label should reflect what the data represents.

**Comment by workergnome** [comment]
Hey, Charlie--

(Apologies for terseness--on a phone)

Looking through AAT, we had to choose a predicate to represent this concept. I explicitly did not choose "sex", because my review of the partner data and conversations with several indicated that the concept represented by partner data was not biological sex, but rather performed sex role, so that's the AAT facet we associated this with. 

I also chose not to specify any specific terms for this--rather, it's a free property designed to pull from any thesaurus of terms. (There's a issue in the mapping, in that it should be an attribute assignment and not a typed-type, but that's a different problem.)

Sex role as a temporally mutable concept is...philisophically difficult to reconcile with an event and entity-based model.  The ways that occur to me where you could model this is either as a entity transformation, where the entity converted to a new entity with different intrinsics, but I'm not sure I agree that someone performing a different sex role is an intrinsically different person. 

The other way to do this is through full reification, where entities are only associated with properties during events. (This also comes up with, say, name changes, or changes in nationality over time.). While doable, we definitely don't have this data, and it would significantly impact usability. 

We have no examples of this, but we could change the model to allow for multiple sex role assignments, much like names, with the option to specify a (institution) preferred role.

Lastly, we could choose to not model this information, but doing so prevents us from doing any analysis of, say, the changes in acquisition patterns for female artists over time, which seems like a large loss. 

Regarding the label of the field--I've tried to stay consistent with the CDWA field names whenever possible, which is why it is "Gender", to match http://www.getty.edu/research/publications/electronic_publications/cdwa/28person.html#gender. While we don't exactly follow those guidelines, it does help provide clarity to institutions who do use those guidelines. 

Hope this helps clarify the decisions as they were made...happy to continue to discuss

**Comment by cbutcosk** [comment]
David,
Thanks for indulging my somewhat under-caffeinated thoughts above. I misread the Gender query--you're right that it's a free property, I had thought it was checking against the 'male' and 'female' terms in the aat.

Allowing multiple values in the gender field would solve this issue for me for now. For the same reasons that it's important to be able to ask questions about works by female artists, I'm trying to make it possible to surface works by queer and transsexual artists. Wikidata has some categories that are a start--"Transsexual artists" and "LGBT artists by nationality" exist, but are stubs. Few matches to the AAC set that I notice (though the AAA has records relating to Candy Darling), but we'll see.

For modelling (looking infinitely down the road) I imagine these are actually two issues: artists with intrinsic properties of particular genders (with potential changes during the entity's lifetime) and the adoption of an alter ego with an alternate/different gender. A transformative event might actually reflect the ontological truth of the former (if not its juridical truth--they're still the same legal entity) while the latter seem like an event akin to a performance, only stretching across years.
