### ISSUE TITLE
mapping for Responsible Department

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/aac_mappings#52]
The [mapping for Responsible Department](http://review.americanartcollaborative.org/entity/E22_Man-Made_Object#field_18-search_0) doesn't show as image, instead "Welcome to PlantUML".

The mapping itself:
```ttl
?entity_uri a crm:E22_Man-Made_Object ;
  crm:P46i_forms_part_of _:collection_class .
_:collection_class a crm:E19_Physical_Object ;
  rdfs:label ?collection_name ;
  owl:sameAs ?collection_class ;
  crm:P49_has_former_or_current_keeper _:department_class .
_:department_class a crm:E74_Group ;
  crm:P2_has_type <http://vocab.getty.edu/aat/300263534> ;
  owl:sameAs ?department_class ;
  crm:P107i_is_current_or_former_member_of ?institution;
  rdfs:label ?department_name .
```
Has these problems:
- why `P49_has_former_or_current_keeper` and not `P50_has_current_keeper` ?
- why not a direct link to the department but go through some imaginary Collection?
- why the collection is `E19_Physical_Object` and not `E78_Collection`?
- the `owl:sameAs` are not specified, so let's see what the students make out of them

**Comment by VladimirAlexiev** [comment]
Predictably, there are no `sameAs` statements, http://yasgui.org/short/SkyPR-y9e

**Comment by workergnome** [comment]
Ignore the `owl:sameAs` statements in the queries generated by the review tool—they're artifacts left over from an experiment in the mapping tool and they're ignored throughout the actual mappings.  

We don't use P50 or a direct link, because when an object is loaned to another institution, the custody of the object is transferred to that institution.  They have temporary custody of the object during that time, and it wouldn't make sense to invalidate the fact that it is still part of the department every time it goes on loan.

Regarding why we don't use `E78_Collection`:  This should be taken up with the CIDOC-CRM.  They seem reasonably adamant that 'collections of objects are `E19_Physical_Object`s, and that Collection has a very specific meaning involving curation and a collection plan, and our understanding is that the departments aren't doing that specific type of activity.   Personally, I think there should be a class for "human-selected collections of objects", but the CIDOC-CRM disagrees with me.

**Comment by azaroth42** [comment]
Yep. Hands are tied. Propose close.

**Comment by VladimirAlexiev** [comment]
- So why not use a direct P49 then?
- A department doesn't curate the collection it's responsible for? That is crazy
- The mapping for Responsible Department STILL doesn't show as image, instead "Welcome to PlantUML"

**Comment by workergnome** [comment]
Because even with a P49, I couldn't tell which of the many possible former holders is the responsible department.  The only way I can think to do without ambiguity it is to generate the departmental collection.

As far as the E78_Collection thing—I agree it's stupid.  But from my understanding of the scope notes and museum practice, it's not appropriate.  My assumption is that the CRM's definition of a "particular collection development plan" and a museum's definition of a "particular collection development plan" are different enough that they're not compatible except for entire museum collections.

**Comment by workergnome** [comment]
(And the Responsible Department is already a known bug, #35).

**Comment by VladimirAlexiev** [comment]
- You don't track any loans, do you?
- About Collection: you could always argue to death. How's a museum collection a Collection, but a departmental one is not?
